### PR TITLE
Jane tried GLM. Was sad.

### PR DESCRIPTION
**Pull request by janewliang**
Very basic stuff. Includes a script file using naive convolution with TR=2 and a test file.

### CODE REVIEW

**Comment by benjaminleroy** [comment]
Who makes a design matrix like that? - I thought we were all stat majors :P.  Also, since sys.path.append  changes the actual PATH file (locally at least), isn't that more dangerous that os.chdir which is very similar to cd? Pitch the benefit please :)

**Comment by benjaminleroy** [comment]
Also Jane, if you have free time to play with, could you incorporate basic hypothesis tests for $\beta_1$ values?    And Later we might look into playing with multiple hypothesis testing (Benjamini–Hochberg)?

**Comment by janewliang** [comment]
Design matrix: are you referring to how I did [convolved 1] instead of [1 convolved]? Because I thought that was weird too, but they did that in the class notes. I can change it to the standard convention, though. Or were you referring to something else. 

sys vs. os: For me, I sort of dislike switching directories when I'm in a Python (or whatever other programming language) session. I like to always assume that my current directory is whatever one the code file I'm working on is stored in. So it was just a personal convention, and I can switch to os if that's preferred, either for the reasons you outlined or for personal conventions. 

Hypothesis testing: Shouldn't be too hard, will try to get it done by the end of the day.

**Comment by benjaminleroy** [comment]
Yes, I was giving you sass for [convolved 1], I'm ok with either but figure if we do it the way we expect [1 convolved], it might stop us from making mistakes (either way we just need to be consistent). Also, I respect to argument for sys (and since it is only a temporary change, lets try to use sys across the board)

Also, hypothesis testing can be done later (don't need to do it now, feel free to do other stuff this weekend)

**Comment by janewliang** [comment]
I'm going to change it to [1 convolved] because the other way around is just too weird/confusing and might get confusing if we hypothetically added more predictors to turn it into a multiple regression problem. 

Ill leave sys for now, but we should maybe talk about how we're going to handle path variables and stuff on Monday so we can be consistent.

**Comment by hiroto-udagawa** [comment]
I second the sys and the [1 convolved]. [1 convolved] should be our standard method as well as column vectors. And sys makes more sense for me too.

**Pull request merged**
