### PR TITLE
noise_correction: Cosine/Fourier + Drift

### PR DESCRIPTION
**Pull request by benjaminleroy**
Initial approach to correcting for noise with basic drift and cosine/fourier series features into the glm paradigm.

Weak test script, but the functions are so trivial....

### CODE REVIEW

**Comment by benjaminleroy** [comment]
- Cool pictures if you fork it :)

**Comment by janewliang** [comment]
Yeah, looks good. The functions themselves don't seem too involved, so I'm fine with the weak tests.

**Comment by kentschen** [comment]
The outputs are great visuals

**Comment by janewliang** [comment]
Awesome.

**Pull request merged**
