### PR TITLE
Benjamini-Hochberg

### PR DESCRIPTION
**Pull request by reychil**
I've made the function (optimized like how @benjaminleroy and I discussed the other day), made a script that will draw out the visualization, and included the test file that I used. Can someone verify that it runs as a whole though? I did it line by line because my computer has issues.

### CODE REVIEW

**Comment by janewliang** [comment]
It seems that you're getting a Travis build error because there is an indentation error in test_bh.py. 

I also tried running your script and got an error: 

Traceback (most recent call last):
  File "bh_script.py", line 104, in <module>
    significant_pvals = bh_procedure(p_vals, Q)
  File "../functions/benjamini_hochberg.py", line 42, in bh_procedure
    if p_sorted[i] < upper[i]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by benjaminleroy** [comment]
Yes there are a few errors, 

1) line  31-ish "img = nib.load(pathtoclassdata + "ds114_sub009_t2r1.nii")" needs to be indented correctly
2) line 18-ish "from hypothesis import t_stat" need to be after sys.path
3) I find that the p_vals need to be the correct shape:
   i) line 41 change "pval=p" to "pval=p.T"
   ii) in first assert:  "assert_almost_equal(np.ravel(pval), useless_bh)"
   iii) in second assert: "assert(not (np.all(np.ravel(pval) != real_bh)))"
in the function:
   iv) "p_sorted = np.ravel(p_sorted)" after "p_sorted = np.sort(p_vals)"
   v) and "return np.array(final_p)"

A lot of the above changes deal with incorrect assumptions of shapes of np.arrays

**Comment by janewliang** [comment]
Nice! I vote to merge. 

ETA: Wait, no. See comment below on script.

**Comment by benjaminleroy** [comment]
Could you make changes in the script file as well?

**Comment by janewliang** [comment]
ETA to before: your script file still has errors. 

Beginning the Benjamini-Hochberg procedure now.
Traceback (most recent call last):
  File "bh_script.py", line 104, in <module>
    significant_pvals = bh_procedure(p_vals, Q)
  File "../functions/benjamini_hochberg.py", line 43, in bh_procedure
    if np.all(p_sorted[i] < upper[i]):
IndexError: index 2 is out of bounds for axis 0 with size 2

**Comment by benjaminleroy** [comment]
For script file:

1) include:  "from Image_Visualizing import present_3d"
2) around 101: "p_vals = p.T"
3) around 110: "reshaped_sig_p = np.reshape(significant_pvals, data.shape[:-1])"   ***\* the shape of the pvalues is a single 3d slice, not a 4 dimensional object

from the above comment 
4) you should really plot:  plt.imshow(present_3d(reshaped_sig_p))  (~ 114)
5) get ride of the plot.clim for that plot, it doesn't make sense

6) Look at the plot that you make in 4,5, what should you do with that stuff... (hint hint)

Also the last plot isn't super helpful

**Comment by janewliang** [comment]
Script runs fine with no errors now. Nice job.

Do you know what's up with the block of significant p-values in the lower right corner? Or how exactly are you supposed to interpret the image?

image

**Comment by benjaminleroy** [comment]
- the block at the bottom is just due to lack of slices (34 instead of 36)

**Comment by janewliang** [comment]
Gotcha. Thanks.

**Comment by janewliang** [comment]
Would it be helpful to draw lines to separate the different slices with grid lines or something?

**Comment by reychil** [comment]
I'm gonna do a mask of the pvalues over the brain imaging. I want to put that into bh_script so don't close/merge anything yet please!

**Comment by janewliang** [comment]
The masked plots look really good. Okay to merge?

**Comment by benjaminleroy** [comment]
no

**Comment by reychil** [comment]
Not yet @janewliang. @benjaminleroy suggested a second masking function in addition to @hiroto-udagawa's

**Comment by hiroto-udagawa** [comment]
@reychil  answering rachel's question to me here since it may be relevant to everyone.

The only thing that my make mask function does is fix the resolution. The mask data was 128x128x34 while our data was 64x64x34 so I needed a way to adjust that. Otherwise, the only thing i do in my mask is multiply the original brain array by a [0,1] masking array. This works for my case with hypothesis testing because a value of 0 is neutral.

**Comment by benjaminleroy** [comment]
@hiroto-udagawa when we do it over a array of all 1s it give 4 different values back (if you were to look at a histogram), do you know the reason for that?

**Comment by reychil** [comment]
WHY IS IT FAILING COVERAGE/COVERALLS????

**Comment by hiroto-udagawa** [comment]
@benjaminleroy uhhh yeaaaa.. that might be because the function is kinda stupid. sorry.. didn't write it very smart. it might be a good idea to go back and make a new better masking function

**Comment by janewliang** [comment]
@reychil I think Coveralls is failing because coverage technically decreased a little, even though 94.569% is still quite good. None of your tests test for the case that no p-values are less than the upper bound, which is why coverage is down slightly.

**Comment by reychil** [comment]
Okay, making a test for that should be pretty trivial. I'll do that sometime this week.

**Comment by benjaminleroy** [comment]
Are we closing this merge request?

**Comment by janewliang** [comment]
@reychil Are all the commits in this pull request also included in your other pull request (which had commits for BH and for the report)?

**Comment by benjaminleroy** [comment]
Looks good

**Comment by janewliang** [comment]
Awesomesauce.

**Comment by benjaminleroy** [comment]
@jarrodmillman  Look at all the conversation

**Pull request merged**
