### PR TITLE
Main script

### PR DESCRIPTION
**Pull request by hiroto-udagawa**
The convolution and the glm scripts are working.

The conclusion script is mostly working but will obviously continue to be a WIP.

Still need to finish up the normality script

### CODE REVIEW

**Comment by hiroto-udagawa** [comment]
for some reason there are 2 glm_final.py in the files changed section. I'm not sure what happened. but might have to to delete one of them later

**Comment by janewliang** [comment]
Super great work. Thanks for this. The Travis build fail for Python 2 seems to be due to connection timing out, which seems weird. I imagine that this is probably something funny on Travis's end, and not our code, so it's probably fine.

**Comment by hiroto-udagawa** [comment]
yes i'll look into it tonight/tomorrow. thanks for the kind words  @janewliang

**Comment by benjaminleroy** [comment]
You have multiple files due to script vs scripts. - make sure to save correct version one of the Homs isn't correct.

**Comment by janewliang** [comment]
In your scripts, why is sub_list defined as sub_list = os.listdir(path_to_data)[1:] with the [1:]? At least on my computer, sub_list = os.listdir(path_to_data) gets you the subject directory names for all 24 subjects exactly, so doing [1:] skips past the first subject.

**Comment by benjaminleroy** [comment]
On ours we have a weird ".blah" file first.   (\* it's called something else, but I don't remember)
Probably should just write it out then

**Comment by janewliang** [comment]
Oh. okay then. I'd probably trust your data before mine, because I've had to break it up and move it around a bunch of times for storage issues.

**Comment by benjaminleroy** [comment]
Well, we can change it anyway (just in case the professor has a similar experience)  -> or maybe we can just ask him

**Comment by hiroto-udagawa** [comment]
I removed the extra files and the main script is mostly running now. just need to add the benjamini hochberg. But i think that this can be merged for now and we can have another pull request with more tweaks.

**Comment by benjaminleroy** [comment]
Looks sexy, also (we chatted about a few changes via slack and now it's good to go)

**Pull request merged**
