### PR TITLE
clustering code with data that I tested on

### PR DESCRIPTION
**Pull request by hiroto-udagawa**

### CODE REVIEW

**Comment by janewliang** [comment]
What's a .npy file? You've added two in your commit, alongside the cluster script (which looks very nice).

**Comment by benjaminleroy** [comment]
a .npy file is a way to save you numpy arrays

**Comment by hiroto-udagawa** [comment]
yea this isnt done yet. just wanted to create the pull request. but i created an array to do clustering on and saved it as a npy file

**Comment by benjaminleroy** [comment]
Can this be approved?

**Pull request merged**
