### PR TITLE
Latex

### PR DESCRIPTION
**Pull request by benjaminleroy**
Updates to my parts of the paper (assuming others will do shared stuff first)

### CODE REVIEW

**Comment by janewliang** [comment]
Looks good, will probably merge soon since I'm one of the people working on shared stuff with you.

**Comment by benjaminleroy** [comment]
Yeah Jane, feel free to merge this, a lot affects you.

**Comment by hiroto-udagawa** [comment]
*affects

**Comment by benjaminleroy** [comment]
I'm an idiot. Thanks for correcting me. I don't know what I'd do without you.

**Comment by janewliang** [comment]
Thanks for that key correction.

**Pull request merged**
