### PR TITLE
Hypothesis testing and clustering latex

### PR DESCRIPTION
**Pull request by hiroto-udagawa**

### CODE REVIEW

**Comment by hiroto-udagawa** [comment]
just a draft, please don't merge yet

**Comment by benjaminleroy** [comment]
Hey, I didn't realize the t-values were so high... that seems wrong...

**Comment by hiroto-udagawa** [comment]
yup i realized this too. i'm trying to figure it out. this didn't happen with data that wasn't smoothed though. it's not completely absurd that they are high though.

**Comment by benjaminleroy** [comment]
ok, but what you are seeing is toooooo many high points.

**Pull request merged**
