### PR TITLE
Create function for hypothesis testing beta values

### PR DESCRIPTION
**Pull request by hiroto-udagawa**

### CODE REVIEW

**Comment by janewliang** [comment]
Haven't tried running it or anything, but it looks good. Should we try to somehow consolidate this with the other GLM functions, since you seem to be re-calculating the betas?

**Comment by reychil** [comment]
Update the description for hypothesis_script.py to make it clear that you're using t_stat() at the bottom of the script. Same thing for test_hypothesis.py - update the blurb at the top from the glm functions

**Comment by benjaminleroy** [comment]
Why did you include the ipython notebook file?

**Comment by hiroto-udagawa** [comment]
The comments on the files are changed 

@janewliang  I think that isnt a bad idea. If that turns out to be a better case, lets implement that later. 
I think we should get a better idea of how we want to use it once we get the convolution and time stuff figured out and we start applying GLM and hypothesis testing to other things.

@benjaminleroy  The iPython notebook stuff was being I was just playing around with it when I was on the branch and I think I accidentally changed a line or two... Is this a big deal? I hope not but if so I can delete it

**Comment by benjaminleroy** [comment]
@hiroto-udagawa  change of notebooks are fine :+1:

**Comment by benjaminleroy** [comment]
@hiroto-udagawa  My test file doesn't run, why is it "pathtoclassdata = "**../**../../data/ds114/"  
(with 3 "../" not just 2). Other than that change I'm ready to merge.

**Comment by benjaminleroy** [comment]
I totally messed this up (now I'm testing things from stack exchange - like this post

**Comment by benjaminleroy** [comment]
I've changed the test file (test_hypothesis) to take into account some examples from the lecture (btws this function is just hypothesis for linear regressions.)

**Comment by benjaminleroy** [comment]
yay!

**Pull request merged**
