### PR TITLE
Fix subject paths.

### PR DESCRIPTION
**Pull request by janewliang**
This hopefully addresses Issue #212. @rossbar 

For anybody who cares: it appears that a few of the files were using the old method for getting all subject paths. Nobody picked up on this, because we all had the old data saved from previous runs. Also, some people put ".nii" instead of ".nii.gz" in their BOLD file paths-- the files should have an ".nii.gz", extension. This may also be the source of the problem.

### CODE REVIEW

**Comment by rossbar** [comment]
I just added a remote to janewliang's repo, checked out the subpaths branch (commit e8def91) and re-ran `make analysis`. Now I get a different IOError, but it's still not working.

**Comment by janewliang** [comment]
What's the error message?

**Comment by rossbar** [comment]
```
Smoothing data, with sigma=1:  [-------------Traceback (most recent call last):
  File "smooth_final.py", line 59, in <module>
    img = nib.load(path_to_data + name + "/BOLD/task001_run001/bold.nii.gz")
  File "/usr/local/lib/python2.7/dist-packages/nibabel/loadsave.py", line 44, in load
    return guessed_image_type(filename).from_filename(filename, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nibabel/loadsave.py", line 76, in guessed_image_type
    with BinOpener(filename) as fobj:
  File "/usr/local/lib/python2.7/dist-packages/nibabel/openers.py", line 120, in __init__
    self.fobj = opener(fileish, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nibabel/openers.py", line 63, in _gzip_open
    gzip_file = BufferedGzipFile(fileish, *args, **kwargs)
  File "/usr/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '../../data/ds009/sub001/BOLD/task001_run001/bold.nii.gz'
```

**Comment by janewliang** [comment]
That's definitely really weird. I doubt that the problem is the file path in smooth_final that's at fault. The other subjects' BOLD data were accessed using the same method for getting file path names, and at least 10-15 or so of them seemed to have done it correctly on your computer (I'm not getting this error message at all) before failing for Subject 1. I can go re-download and unpack the data from OpenfMRI to see if they've changed it or something since we first downloaded it for this project, but that's the only thing I can think of.

**Comment by rossbar** [comment]
I will delete the data and try to re-download to see if that helps... stay tuned

**Comment by rossbar** [comment]
Now I've run out of drive space (not your fault, I'm trying to run several projects at the same time)... I won't be able to test it til later. If one of your group members manages to get this to succeed with a fresh install (i.e. reclone the project and run through the make steps successfully), please merge this PR and notify me

**Comment by janewliang** [comment]
@rossbar We're downloading and checking out the data, so we'll get back to you, but if you check the hashes of your data by calling "make validate" in the data directory, an error should also be raised if a file that is saved in the dictionary of file hashes (ds009_hashes.json) is not present in the right place. ds009_hashes stores the file names and hashes ask key-value pairs. I created it based on the data stored on my computer, so it does have  a BOLD file saved at "project-alpha/data/ds009/sub001/BOLD/task001_run001/bold.nii.gz". 

image

**Comment by rossbar** [comment]
The hashing checked out so it wasn't that. I probably screwed it up when I tried to fix it the first time around. My suspicion is one of my changes caused the data to be unzipped but then when it still failed, that file, which your code was expecting to be a .gz had already been unzipped on disk.

**Comment by janewliang** [comment]
Cool. Then hopefully things will run with my fixes after redownloading the data. Sorry for all the confusion! Let us know if you're still getting errors.

**Comment by rossbar** [comment]
Almost made it all the way through this time. Here's the most recent error:

```
Traceback (most recent call last):
  File "event_related_plots.py", line 61, in <module>
    cond_all=np.loadtxt(condition_location+"cond_all.txt")
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 738, in loadtxt
    fh = iter(open(fname, 'U'))
IOError: [Errno 2] No such file or directory: '../../data/ds009/sub001/model/model001/onsets/task001_run001/cond_all.txt'
```

**Comment by janewliang** [comment]
That should do it. Sorry! 

@benjaminleroy would like to say "dang it- that was my fault". And it was, but we still should have caught it.

**Comment by janewliang** [comment]
Merging this, because it should address at least some of the reproducibility issues.

**Pull request merged**
