### PR TITLE
Hypothesis

### PR DESCRIPTION
**Pull request by benjaminleroy**
Added functions to t statistics functions for multiple regression, as well as tests for such things. Updated script file for t statistics to reflect multiple options for convolution function.

@hiroto-udagawa

### CODE REVIEW

**Comment by benjaminleroy** [comment]
Damn, I keep being sloppy, this pull request contains updates for the glm stuff as well, can't push until the glm stuff is oked. Sorry.

@janewliang

**Comment by janewliang** [comment]
I think this is okay! We seem to have some merge conflicts, though.

**Comment by benjaminleroy** [comment]
@janewliang look, I fixed the conflict :). @hiroto-udagawa is this useful now?

**Comment by janewliang** [comment]
Good job!

**Comment by hiroto-udagawa** [comment]
i think its good to have!

**Pull request merged**
