### PR TITLE
Timeshift2

### PR DESCRIPTION
**Pull request by janewliang**
Redux with less stuff. 

Pretty basic. The script uses np.convolve on our data and the test uses np.convolve on the class data. Can update with @benjaminleroy fancy convolution later after discussion.

### CODE REVIEW

**Comment by benjaminleroy** [comment]
I approve of the changes made to the convolution functions- should have updated those myself :). Figure @reychil can approve the small changes made to smooth. The time series stuff looks good (in a sense that I didn't run them)

**Comment by janewliang** [comment]
@benjaminleroy It was basically the exact same thing I showed you yesterday. We should probably discuss next week about your convolution stuff and update the time shift script later.

@reychil You checked the that null case for smoothing (fwhm = 0) doesn't change anything, so I checked that if fwhm != 0, the data should at least be different (idk how you would check it was the "correct" smoothing).

**Comment by benjaminleroy** [comment]
Ok, I'm ok will the updates to the convolution, and since we can update the rest later (and will-do in the real script, I don't see lots of benefits to wait for those). Rachel's stuff would be why I'd wait (just to check in with her)

**Comment by janewliang** [comment]
Also adding tests for glm_diagnostics (residuals, fitted values, etc) since my other pull request looks like a hot mess.

**Comment by janewliang** [comment]
Really just want to go figure out my other pull request, so merging and closing this for now.

**Pull request merged**
