### PR TITLE
Fourier Correction

### PR DESCRIPTION
**Pull request by benjaminleroy**
**Updates to a lot of codes because we decided last minute to switch to Fourier analysis**. Mostly looking for feedback, did create a few additional files to (in the future be done on a "div" branch). We will need to delete the "fourier" add-ons, but this is slightly for save-keeping.

**Also happened to change some basic things in latex related to images**.

@janewliang Looksy

**Why?**
We've discovered that PCA is too powerful. And we are firm believers that weakness is a strength. And so we've gone with Fourier. 

**For those who I haven't talked to about this**, we this the PCA vectors we collinear to the hrf or otherwise causing it to act out for some people (possibly overfitting when the variance explained by the first 6 pcas were very high). I compare the outcomes (in terms of t-statistics and beta values) for we used Fourier 6 instead of PCA 6 and we saw some were super similar to the PCA versions and some were very different (but is a good way). Moreover we know that Fourier is pretty unlikely to overfit by construction (and even more unlikely to be very collinear with the hemodynamic response. I did add 6 Fourier features instead of 4.... sorry.

All in all, I think this is a good improvement on end results.

### CODE REVIEW

**Comment by reychil** [comment]
Where exactly did you do the Fourier analysis? You changed a lot of files but I'm having difficulty finding which file exactly. The bh_t_beta files that we worked on last Thursday look the same to me right now

**Comment by benjaminleroy** [comment]
Most files I changed a lot have _fourier after them. There are a few new
ones, but in general it's not new ideas per se

**Comment by benjaminleroy** [comment]
Dear all,

I hope this finds you well. Having spend 12+ hours after our meeting on Wednesday cleaning up and finding why overlapping of our Benjamini Hochberg multiple comparison of p-values, and the other thresholds using upper quantiles of abs(t-statistic) and abs(beta) were not providing accuracy results to find locations of activations regions. 

 My **first conclusions** where 2 fold;
(1) that the brains fail to line up enough that a lot of the area interpretation is lost via this problem alone and 
(2) the certain subjects linear regression models overfit, and inclusion of 6 principle components created collinearity with our predicted Hemodynamic response function. These generally occurred when the variance explained by these principle components where much larger than our lower threshold of .4 (40% variance explained)  *\* recall this is all in terms of principle components of the A^T A matrix , where A is the masked voxel time courses.

## Introduction of Fourier

In attempts to correct for this problem (of overfitting/collinearity), and with a firm understanding that the 6 fourier features would fail to introduce such collinearity and explanation of variance, I ran models with 6 fourier features instead. Let’s call this model “_fourier”.

For the subjects with ~40% variance explained by the first 6 principle, the beta values and t-statistics from this new model (“_fourier”) compared to the old model (with the 6 principle components “_pca”). Impressed by this outcome (as we saw earlier that _fourier was less able to predicted the BOLD response than the _pca model in the model selection analysis). I decided to implement the analysis for all subjects

## Parameter Selection for “multiple comparison” and threshold analysis

While trying to find a single set of parameters to utilize across all subjects for all of these analyses, I discovered that for Benjamini Hochberg the Q value was much more variable or each subject than the other threshold analysis. And as such, even though Benjamini Hochberg is more theoretically sound, it is less strong in our case.

**Recall** that Benjamini Hochberg requires a Q (generally thought of as an \alpha value) and # of neighbors selection for neighbor smoothing, and our threshold statistics require an quantile value of the proportion of values saved, and a # of neighbors for neighbor smoothing.

In general, the data fails to provide many regions of activation, as the only current method for such analysis is now requires per subject analysis separately (by eye), the charts to find these patterns can be created by running “image_outlay_final.py”. As such, our conclusions should probably only include identification of the frontal lob (@kentchen, I still need the full range of possibilities of actual activation locations created for at  “sub001” at least)

## Basic “Bro” Conclusion

In general the only thing that sticks out to me is the frontal cortex as previously noted. #BasicBro

******\* Please review/comment and add my stuff

**Comment by janewliang** [comment]
This all feels far more like art than science at this point (since, to be frank, our biggest motivation and metric for deciding which models/parameters to use is by visual inspection on the per-subject base, which does not lend itself well to future extensions and reproducibility). But I support the Fourier argument, which had already been raised several weeks ago: Fourier has better justification than PCA, even though the model selection seemed to favor PCA. And since our goals are to model/identify active regions rather than prediction, I think that good interpretability is key.

**Comment by reychil** [comment]
I also think your reasoning and conclusions for the Fourier process is justified. Some parts of your explanation could be better worded, I think, but that'll probably just be cleared up when we go through the paper one last time. I don't really remember what the motivation to use PCA over fourier analysis was when we were at that crossroads, but it's awesome that you backtracked.

**Comment by janewliang** [comment]
Really great work. I'm going to merge.

**Pull request merged**
