### PR TITLE
shapiro wilks

### PR DESCRIPTION
**Pull request by kentschen**
shapiro wilks works

### CODE REVIEW

**Comment by benjaminleroy** [comment]
might you put the 4 lines in a wrapper function? This way you an make a test file a well to show it works.
Would be better for when we wish to use it for all the residuals. Also you could mirror this with a wrapper function for the other normality test. Also, in the script examine the output (plots), so you can get a conclusion of potential multiple comparison problems.

**Comment by kentschen** [comment]
Landed safely and worked on this during the 14 hour flight Internet-less and without a power outlet. Got a couple questions/clarifications:

1) Am I taking the right approach into the function wrappers/decorators in the normality.py file? The wrap, trace_in, trace_out works but I need some feedback for code review to see if I'm on track or off track, especially after the @wrap part. Is there a better way of doing it instead of three straight "if" statements?

2) For the functions, should I go about using "if" statements on the conditions of i, j, k OR "for" statements? For Shapiro-Wilks, when I do "for" statements, I just get an output of (1.0, 1.0) which is not desired output. However, when I did it with "if" statements, I got my expected output ONCE (0.98..., 0.013...) but since then, I've been getting a message that "name 'i' is not defined". For Kruskal-Wallis, I got something like (0.0, nan) which appears to be some ValueError. Please advise on what step(s) I'm missing out on.

Thanks!

**Comment by reychil** [comment]
The first error I see on Travis is that you're using the print function call for python2, in python 3, the print function call looks like -> print("something to print")

You're getting "name 'i' not defined" in your normality file because you haven't declared it as a variable. If you're trying to reference each point in the data or something you probably have to use a for-loop over the range of the length of each dimension. 

One last note - just for consistency, could you name your script file normality_script.py or something like that?

**Comment by janewliang** [comment]
@kentschen , glad to hear you landed safely and got some work done.

I think that when @benjaminleroy talked about wrapping your code, he just meant to put in the for loop you originally wrote into a function that could be called on new data sets, not to wrap it with the decorators. E.g. 

```
def normality(resid_4d):
    initialize 3-d arrays for storing shapiro wilks and kruskal wallis
    for i in 1st_dim_of_resid_4d, j in 2nd_dim_of_resid_4d, k in 3rd dim_of_resid_4d: 
        shapiro_wilks_3d[i,j,k] = shapiro_wilks_fun(resid_4d[i,j,k,:])
        kruskal_wallis_3d[i,j,k] = kruskal_wallis_fun(resid_4d[i,j,k,:])
    return shapiro_wilks_3d, kruskal_wallis_3d
```

You should definitely be using "for" (or some kind of loop), and not "if" (or some kind of control flow sequence). These are fundamentally different things. You should also have your return statement OUTSIDE of the for loop. The reason why you are not getting answers of the correct dimension is because you are returning within your for loop, so you only iterate once and then you just return Shapiro Wilks for the first voxel. Right now, even if you (correctly) moved the return statement out of the for loop, you would still overwriting the Shapiro WIlks value at ever iteration of the loop. This is why you need to initialize a 3-dimensional array of the same dimensions as the voxel space (e.g. the 1st 3 dimensions of the 4-d residual array) to store all of the Shapiro Wilks values in a DIFFERENT spot every time you do a single loop iteration. We talked about this, so if you are still unclear on what this means and why you need to do it, please let us know. 

You could instead have separate functions, one to do just shapiro wilks and one to do kruskal wallis, instead of putting the two together, etc. Whatever makes the most sense to you. That way, all the script has to do is loop through all the subjects, do GLM, get the residuals, and pop the 4-d residual array into the normality function. Out comes Shapiro Wilks and/or Kruskal Wallis. 

Why do you have both normality.py and normality_script.py in the scripts directory? You should only have one file, normality_script.py, which run the script for our data using the functions in functions/normality.py.

**Comment by janewliang** [comment]
In the future, please also refer to the Python documentation to check what inputs functions expect and what their return values are. This is a fairly straightforward thing to do and a good habit to get into, because it is your job to familiarize yourself with how to correctly utilize the Python modules related to the code you're writing, not the job of the rest of the team to look it up for you when you are stuck.

You will notice that for both the Shapiro Wilk and Kruskal Wallis functions on SciPy, they return multiple values (e.g. test statistics, p-values, etc). You'll need to figure out how to correctly extract the value of interest (probably p-values) and save that to the 3-d array at each iteration. 

You are getting an error for Kruskal Wallis because the function expects you to give it TWO arrays, not one. This is because, unlike Shapiro Wilk which tests for normality, Kruskal Wallis is just testing if two distributions (of any type) are the same. So in addition to the residual data, you need to give it some sample data from the normal distribution. One way to do this for each voxel would be to simulate data from the normal distribution with mean = mean of the residuals for that voxel and standard deviation = standard deviation of the residuals for that voxel. If the residuals for each voxel are approximately normal, we would expect them to follow the simulated distribution.

**Pull request merged**
