### PR TITLE
Updated the data directory to download and check hashes for ds009 data.

### PR DESCRIPTION
**Pull request by janewliang**
@jarrodmillman 
We have a lot of data, so when getting all the file hashes, I saved the dictionary to a JSON file in the data directory (pushed to this branch, so it's accessible to all) and then loaded it in data.py rather than copy-pasting all of the key-value pairs into the .py file itself. So this still meets your basic requirement that "make data" will get you all the data and "make validate" will validate the content, but I was a bit uncertain about whether introducing the external JSON file would still be legal. Also, was there anything to be done by us in the "tests" directory, other than deleting the two superfluous lines from test_data.py?

General notes for everybody else:
Don't actually try running "make data" on your computer because it will try to download all 6 GB of our data and you will cry. If you want to test it out, just make sure you've got the ds009 directory in the data directory. Then, with the data directory as your current directory, run "make validate" or "python data.py". I tried "make data" on my own computer and let it run long enough to see that it was downloading the correct .tgz file, so I'm fairly confident this should work (the tar command to decompress the file is literally the same one I used on the data originally). 

I am currently only checking the hashes for the ds009 data, and not the 4 data files from class. If we end up deciding to use those for our tests, I can add to the Makefile to include downloading and checking those files too, no problem. 

The only failure is coverage, which is apparently around 80%. What's not covered is the contents of if **name** == "**main**" in the data.py file.

### CODE REVIEW

**Comment by benjaminleroy** [comment]
Awesome, We should definitely follow up with Jarrod on the coverages (I haven't checked the code, so this isn't a vote to merge)

**Comment by janewliang** [comment]
Update: Added tests. Coverage is like 90%.

**Comment by benjaminleroy** [comment]
@jarrodmillman @rossbar   It seems as we update the master (accept push requests) and then continue updating a open pull directory we get more and more files that says they are being changed. How do we deal with that? (This directory has 11 "changed" files, but only really 6 files that are being updated).

@janewliang It looks like it does the right thing, would you like me to grab this branch and run it on my computer?

**Comment by janewliang** [comment]
@benjaminleroy That would be great! Yeah, try both validating the hashes on your data and also run the nosetests. 

@jarrodmillman @rossbar Is there some kind of minimum coverage that we're supposed to attain? Because, for example, this branch has decreases coverage to 92.8%, but the uncovered stuff is pretty silly (stuff that gets called only when executing the file, and also a try statement that checks whether libraries for Python 2 or Python 3 should be imported).

**Comment by benjaminleroy** [comment]
@janewliang I was able to run the validation of the the hashes for the data and nosetests were successful. I'm afraid I don't understand it all, but it runs well I'm ok approving even with coverage decrease. Good job.

**Comment by janewliang** [comment]
Cool, I can walk you through what I did during tomorrow's meeting.

**Comment by kentschen** [comment]
Tests passes Travis CI and Coveralls

**Pull request merged**
