### PR TITLE
Outliers

### PR DESCRIPTION
**Pull request by janewliang**
Comparing mean MRSS from doing simple linear regression on the np.convolve time course for each subject. Uses the extended RMS method from HW2. Generally doesn't seem like it makes much of a difference, which would argue against using this method to identify outliers.

### CODE REVIEW

**Comment by janewliang** [comment]
Added script to get explained variance plots for PCA.

**Comment by janewliang** [comment]
@jarrodmillman Can we get sklearn added to whatever thing Travis installs its dependencies from please? That would be awesome, thanks.

**Comment by benjaminleroy** [comment]
let's talk to Jarrod about this tomorrow

**Comment by janewliang** [comment]
@jarrodmillman Could you add sklearn? Travis is failing when we add "sklearn==0.17.0" to the requirements.

**Pull request merged**
