### PR TITLE
Updates for glm_test.py and validating test data

### PR DESCRIPTION
**Pull request by janewliang**
1. Added tests to specifically see if glm_diagnostics in glm.py produces the correct residuals, fitted values, and MRSS given the estimated betas and the design matrix.
2. Added a validation process for the test data (the ds114 data from class) to the data Makefile. Basically does the same thing as the validation process for our data (ds009), but with the ds114 data instead. 
3. Renamed the Makefile recipes for the test data do it's less ambiguous. They're now called testing_data and testing_validate, since "test_*" seems to be our go-to naming convention for test files and I wanted to clarify that neither of those recipes tests anything, they just work with the test data.

### CODE REVIEW

**Comment by janewliang** [comment]
This inadvertently turned into a pull request about reconfiguring our test and coverage recipes in the main, data, and code Makefiles. But all recipes should work now when you call "make [proc]" from the same directory that the Makefile is located in. For some reason, Travis refuses to update the coverage, but our new coverage should be both (a) a better reflection of what we've done (since it only checks the coverage of our functions) and (b) higher. I expect it'll go up even more once we merge Rachel's smoothing test, since smoothing currently has 0% coverage.

**Comment by benjaminleroy** [comment]
Coverage error?

**Comment by janewliang** [comment]
@jarrodmillman @rossbar Do either of you know why coverage is still pending from Coveralls.io? The Travis build log says that they successfully submitted the coverage report to Coveralls, so I don't know why it's taking forever.

**Comment by janewliang** [comment]
@benjaminleroy It's not a coverage error, it's just still pending for some reason. I did fix our "make coverage" recipe so that it actually worked correctly locally, but I don't know if I somehow screwed it up for Travis. You can see in the build reports what the coverage is (93% for code and 100% for data), and the log says that Travis submitted it to Coveralls, but for some reason it's not updating.

**Comment by janewliang** [comment]
Now the build is failing, but should be okay after we merge my other pull request on time shifts.

**Comment by benjaminleroy** [comment]
Ok -we'll wait on this one until the other is approved (and maybe we talk to Ross/Jarrod Monday/Tuesday).

**Comment by janewliang** [comment]
Closing. Trying again on a fresh branch.

**Pull request closed without merging**
