### PR TITLE
Adding convolution analysis 

### PR DESCRIPTION
**Pull request by benjaminleroy**
Also, I added a visualization function and the stimuli.py.  Sorry the test file isn't the best, try running the plot to see that they're very similar.

### CODE REVIEW

**Comment by hiroto-udagawa** [comment]
Sorry if this is a dumb question, but where are your changes for stimuli.py?

**Comment by benjaminleroy** [comment]
I just threw it into the functions code folder (it wasn't there before)

**Comment by benjaminleroy** [comment]
actually, I guess it is there already?

**Comment by benjaminleroy** [comment]
hmmm... I guess it didn't come along...

**Comment by hiroto-udagawa** [comment]
yes, great idea though. please add it and make it part of the merge. from now on, whenever someone uses stimuli.py they can refer to that

**Comment by benjaminleroy** [comment]
They're now uploaded as well. I'm ok if this takes some time to look over :)

**Pull request closed without merging**
