### PR TITLE
model_comparison 1d functions

### PR DESCRIPTION
**Pull request by benjaminleroy**
@hiroto-udagawa 

Sexy model selection functions (put in a file, because Ben wanted to)

### CODE REVIEW

**Comment by janewliang** [comment]
Annoying notes: 

In comments for adjR2, you wrote "MRSS: Mean Squared Error". I think you mean "MSE = Mean Squared Error"? In which MSE = RSS/n, and so RSS = n \* MSE, not df \* MSE. Further, if you assume df = n - p (n is number of observations, p is number of predictors counting the intercept if applicable), this is the number of degrees of freedom for the RESIDUALS, not the MODEL (which should be p). Analogous comments apply to the BIC function.

In your tests, why the is the \* 2 necessary in MRSS= np.mean((y_1d-np.mean(y_1d)) *\* 2) \* 2?  The \* 2 doesn't make sense to me.

**Comment by benjaminleroy** [comment]
Good notes @janewliang I'll definitely correct them (I'll look into the *2 thing as well, I remember it was needed, just not sure why)

**Comment by benjaminleroy** [comment]
@janewliang 

These should address problems observed by Jane. 

@hiroto-udagawa to make it more theoretically rigorous I've added a "rank" and a "df" input, although you could assume they are related in a defined way, it would smart to use np.linalg's "rank" function.

**Comment by benjaminleroy** [comment]
@janewliang 

MRSS is defined as RSS/df for Regression (or so say wikipedia), I used MRSS (which is the same as MSE) because that's the output for a glm tool you or Hiro made

**Comment by janewliang** [comment]
Thanks for the fixes, Ben! I saw that you had defined MRSS as mean squared error, and just assumed that you had meant to say it was the MSE (M=mean, S=square, E=error), which I want to say has the n denominator (also according to Wikipedia) and is therefore not the same as MRSS. If you're just getting MRSS from the glm functions, that should be fine, and yes, I recall that it's RSS/df.

**Pull request merged**
